# Generated by Django 3.1.2 on 2020-12-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carid', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=200)),
                ('vin', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('mfg_year', models.IntegerField()),
                ('category', models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'SEDAN'), ('SPORTS CAR', 'SPORTS CAR'), ('STATION WAGON', 'STATION WAGON'), ('HATCHBACK', 'HATCHBACK'), ('CONVERTIBLE', 'CONVERTIBLE'), ('MINIVAN', 'MINIVAN'), ('PICKUP TRUCK', 'PICKUP TRUCK')], max_length=200)),
                ('primary_image', models.ImageField(default='none.jpg', upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('skype', models.CharField(default='N/A', max_length=200, null=True)),
                ('whatsapp', models.CharField(default='N/A', max_length=200, null=True)),
                ('membership', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('confirmation_code', models.CharField(max_length=200, null=True)),
                ('avatar', models.ImageField(default='no-one.jpg', null=True, upload_to='customers')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('renerid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('skype', models.CharField(default='N/A', max_length=200)),
                ('whatsapp', models.CharField(default='N/A', max_length=200)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('driving_license', models.CharField(default='N/A', max_length=200)),
                ('license_image', models.ImageField(default='no-one.jpg', upload_to='renters')),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('avatar', models.ImageField(default='no-one.jpg', upload_to='renters')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.car')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('membershipid', models.AutoField(primary_key=True, serialize=False)),
                ('freerides', models.IntegerField(null=True)),
                ('membertype', models.IntegerField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentadmin.customer')),
            ],
        ),
    ]
