# Generated by Django 3.1.2 on 2020-12-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0002_auto_20201220_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='membertype',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=200, null=True),
        ),
    ]
