# Generated by Django 3.1.2 on 2020-12-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0003_auto_20201220_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
