# Generated by Django 3.1.2 on 2020-12-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0005_renter_chauffeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='renerid',
            new_name='renterid',
        ),
    ]
