# Generated by Django 3.1.2 on 2020-12-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0008_riderequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='long',
            new_name='lon',
        ),
    ]
