# Generated by Django 3.1.2 on 2020-12-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0009_auto_20201222_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
