# Generated by Django 3.1.2 on 2020-12-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0010_riderequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.customer'),
        ),
    ]
