# Generated by Django 3.1.2 on 2020-12-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0011_auto_20201222_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.renter'),
        ),
    ]
