# Generated by Django 3.1.2 on 2020-12-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0012_riderequest_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='miles',
            field=models.IntegerField(null=True),
        ),
    ]
