# Generated by Django 3.1.2 on 2020-12-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0013_memberinfo_miles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='miles',
            field=models.IntegerField(default=0),
        ),
    ]
