# Generated by Django 3.1.2 on 2020-12-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0014_auto_20201224_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('payerid', models.IntegerField()),
                ('payer_type', models.CharField(choices=[('Customer', 'Customer'), ('Renter', 'Renter')], max_length=200)),
                ('pay_mode', models.CharField(choices=[('CashApp', 'CashApp'), ('PayPal', 'PayPal'), ('Card', 'Card')], max_length=200)),
                ('paid_for', models.CharField(choices=[('Weekly Payment', 'Weekly Payment'), ('Buy Miles', 'Buy Miles')], max_length=200)),
                ('payment_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
