# Generated by Django 3.1.2 on 2020-12-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0016_payments_txnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='pay_plan',
            field=models.CharField(choices=[('5', '5 Mile'), ('Buy Miles', 'Buy Miles')], max_length=200, null=True),
        ),
    ]
