# Generated by Django 3.1.2 on 2020-12-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0018_auto_20201225_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
