# Generated by Django 3.1.2 on 2020-12-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0021_auto_20201225_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='ridemiles',
            field=models.IntegerField(null=True),
        ),
    ]
