# Generated by Django 3.1.2 on 2020-12-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0022_riderequest_ridemiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('biddingid', models.AutoField(primary_key=True, serialize=False)),
                ('costpermile', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('conditions', models.TextField(null=True)),
                ('cities', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentadmin.renter')),
            ],
        ),
    ]
