# Generated by Django 3.1.2 on 2020-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0025_riderequest_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='gig',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.DeleteModel(
            name='Bidding',
        ),
    ]
