# Generated by Django 3.1.2 on 2020-12-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0027_customergig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergig',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.CreateModel(
            name='Gigride',
            fields=[
                ('gigrideid', models.AutoField(primary_key=True, serialize=False)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('offer_hours', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gigid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.customergig')),
            ],
        ),
    ]
