# Generated by Django 3.1.2 on 2020-12-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0028_auto_20201231_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigride',
            name='offered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.renter'),
        ),
    ]
