# Generated by Django 3.1.2 on 2021-01-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0029_gigride_offered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigride',
            name='status',
            field=models.CharField(default='Accepted', max_length=200),
        ),
    ]
