# Generated by Django 3.1.2 on 2021-01-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0030_gigride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigride',
            name='sattled_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
