# Generated by Django 3.1.2 on 2021-01-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0031_gigride_sattled_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigride',
            old_name='gigid',
            new_name='gig',
        ),
    ]
