# Generated by Django 3.1.2 on 2021-01-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0032_auto_20210102_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.customergig'),
        ),
        migrations.AlterField(
            model_name='gigride',
            name='status',
            field=models.CharField(default='Requested', max_length=200),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_for',
            field=models.CharField(choices=[('Weekly Payment', 'Weekly Payment'), ('Buy Miles', 'Buy Miles'), ('Gig Ride', 'Gig Ride')], max_length=200),
        ),
    ]
