# Generated by Django 3.1.2 on 2021-01-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0033_auto_20210104_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
