# Generated by Django 3.1.2 on 2021-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0036_emailconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='zip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
