# Generated by Django 3.1.2 on 2021-01-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0037_auto_20210111_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='notify_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
