# Generated by Django 3.1.2 on 2021-01-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0038_renter_notify_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='caraccident',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='carprefer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='currentjob',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='drivinghistory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='insurance_image',
            field=models.ImageField(default='no-one.jpg', upload_to='renters'),
        ),
        migrations.AddField(
            model_name='renter',
            name='insurance_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='licenseinyears',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='qualityodriver',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='workedincar',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
