# Generated by Django 3.1.2 on 2021-01-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0039_auto_20210112_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paid_for',
            field=models.CharField(choices=[('Weekly Payment', 'Weekly Payment'), ('Buy Miles', 'Buy Miles'), ('Gig Ride', 'Gig Ride'), ('Car Reservation', 'Car Reservation')], max_length=200),
        ),
        migrations.CreateModel(
            name='CarInterest',
            fields=[
                ('interestid', models.AutoField(primary_key=True, serialize=False)),
                ('interest_type', models.CharField(max_length=200, null=True)),
                ('deposit_amount', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.car')),
                ('renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.renter')),
            ],
        ),
    ]
