# Generated by Django 3.1.2 on 2021-01-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0040_auto_20210113_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.car'),
        ),
    ]
