# Generated by Django 3.1.2 on 2021-01-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0041_payments_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinterest',
            name='interest_type',
            field=models.CharField(choices=[('General', 'General'), ('Reserve', 'Reserve')], max_length=200, null=True),
        ),
    ]
