# Generated by Django 3.1.2 on 2021-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0042_auto_20210113_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
