# Generated by Django 3.1.2 on 2021-01-22 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentadmin', '0045_gigride_sattled_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.CharField(max_length=200, null=True)),
                ('redir_url', models.TextField(null=True)),
                ('notifyfrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_from_set', to=settings.AUTH_USER_MODEL)),
                ('notifyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_to_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
