# Generated by Django 3.1.2 on 2021-02-02 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentadmin', '0047_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.renter'),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('networkid', models.AutoField(primary_key=True, serialize=False)),
                ('branch_renter', models.TextField(null=True)),
                ('branch_customer', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('root_renter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentadmin.renter')),
            ],
        ),
    ]
