# Generated by Django 3.1.2 on 2021-02-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0049_renter_network_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='branch_customer',
            new_name='branch_customers',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='branch_renter',
            new_name='branch_renters',
        ),
    ]
