# Generated by Django 3.1.2 on 2021-02-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0050_auto_20210203_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteJoin',
            fields=[
                ('inviteid', models.AutoField(primary_key=True, serialize=False)),
                ('invite_email', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('invite_type', models.CharField(choices=[('Customer', 'Customer'), ('Renter', 'Renter')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('invite_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentadmin.renter')),
            ],
        ),
    ]
