# Generated by Django 3.1.2 on 2021-02-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0051_invitejoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='join_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitejoin',
            name='invite_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
