# Generated by Django 3.1.2 on 2021-02-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0052_auto_20210203_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitejoin',
            name='invite_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
