# Generated by Django 3.1.2 on 2021-02-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0053_auto_20210203_0232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Network',
        ),
    ]
