# Generated by Django 3.1.2 on 2021-02-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0054_delete_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterNetwork',
            fields=[
                ('networkid', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch_renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_renter', to='rentadmin.renter')),
                ('root_renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_renter', to='rentadmin.renter')),
            ],
        ),
    ]
