# Generated by Django 3.1.2 on 2021-02-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0056_auto_20210204_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNetwork',
            fields=[
                ('networkid', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentadmin.customer')),
                ('root_renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentadmin.renter')),
            ],
        ),
    ]
