# Generated by Django 3.1.2 on 2021-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0057_customernetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notify_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
