# Generated by Django 3.1.2 on 2021-02-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0058_customer_notify_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='ride_network_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
