# Generated by Django 3.1.2 on 2021-02-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0059_riderequest_ride_network_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='ride_network_id',
            new_name='customer_network_id',
        ),
    ]
