# Generated by Django 3.1.2 on 2021-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0060_auto_20210205_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernetwork',
            name='network_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renter',
            name='network_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renternetwork',
            name='network_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
