# Generated by Django 3.1.2 on 2021-02-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0063_auto_20210207_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideShare',
            fields=[
                ('shareid', models.AutoField(primary_key=True, serialize=False)),
                ('network_code', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_by', to='rentadmin.renter')),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentadmin.riderequest')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_by', to='rentadmin.renter')),
            ],
        ),
    ]
