# Generated by Django 3.1.2 on 2021-02-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0067_renter_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='is_shared',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
    ]
