# Generated by Django 3.1.2 on 2021-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0068_riderequest_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='renter',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
