# Generated by Django 3.1.6 on 2021-02-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0072_auto_20210223_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='picklat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='riderequest',
            old_name='picklon',
            new_name='lon',
        ),
    ]
