# Generated by Django 3.1.6 on 2021-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0073_auto_20210223_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(default='Company', max_length=100),
        ),
    ]
