# Generated by Django 3.1.6 on 2021-02-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentadmin', '0074_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance_image',
            field=models.ImageField(default='none.jpg', upload_to='cars'),
        ),
    ]
