from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name="adminhome"),
    path('login', views.userlogin,name="userlogin"),
    path('logout', views.logoutuser,name="userlogout"),
    path('signupmember', views.membersignup,name="membersignup"),
    #path('JoinAsRenter/', views.joinasrenter,name="joinasrenter"),
    path('markasread/<str:id>', views.markasread,name="markasread"),

    path('car/<str:id>', views.cardetails,name="viewcar"),
    path('addcar', views.addcar,name="addcar"),
    path('updatecar/<str:id>', views.updatecar,name="updatecar"),
    path('deletecar/<str:id>', views.deletecar,name="deletecar"),

    path('payrequests/', views.new_payments,name="payrequests"),
    path('acceptpayment/<str:id>', views.accept_payment,name="acceptpayment"),

    path('allcustomer', views.customerlist,name="customerlist"),
    path('customer/<str:id>', views.customerdetails,name="customerdetails"),

    path('createuser', views.createuser,name="createuser"),
    path('demo', views.demo,name="demo"),
    path('imagecheck', views.imagecheck,name="imagecheck"),
    path('imagetest', views.imagetest,name="imagetest"),

    path('customer/home/', views.customer_dashboard,name="customerhome"),
    path('customer/profile/', views.customerprofile,name="customerprofile"),
    path('customer/changeavatar/', views.changeavatar,name="changeavatar"),
    path('customer/changerenteravatar/', views.changeavatar,name="changerenteravatar"),
    path('customer/resendcode/', views.resend_email,name="resendcode"),
    path('customer/varifycode/', views.verify_code,name="varifycode"),
    path('customer/payment/', views.customer_payment,name="payment"),
    path('customer/requestride/<str:lat>/<str:lon>/<str:dstlat>/<str:dstlon>/<str:tp>/<str:ml>', views.request_ride,name="requestride"),
    path('customer/cashapppayment/', views.cashapp_payment,name="cashapppayment"),
    path('customer/paymenthistory/', views.payment_history,name="paymenthistory"),
    path('customer/makegig/', views.makegig,name="makegig"),
    path('customer/giglist/', views.giglist,name="giglist"),
    path('customer/deletegigrequest/', views.deletegigrequest,name="deletegigrequest"),
    path('customer/checkrequests/<str:gigid>', views.checkrequests,name="checkrequests"),
    path('customer/payforgig/', views.payforgig,name="payforgig"),
    path('customer/renterinfo/<str:id>', views.renterinfo,name="renterinfo"),
    path('customer/countergigrequest/', views.countergigrequest,name="countergigrequest"),
    path('customer/infocomplete/', views.infocomplete,name="infocomplete"),
    path('customer/testapi/', views.testapi,name="testapi"),
    path('customer/riderequest/', views.riderequest,name="riderequest"),


    path('renter/home/', views.renter_dashboard,name="renterhome"),
    path('renter/profile/', views.renter_profile,name="renterprofile"),
    path('renter/riderequests/', views.ride_requests,name="riderequests"),
    path('renter/acceptride/<str:id>', views.accept_ride,name="acceptride"),
    path('renter/changerenteravatar/', views.changerenteravatar,name="changerenteravatar"),
    path('renter/completeride/<str:id>', views.completeride,name="completeride"),
    path('renter/gigboard/', views.gigboard,name="gigboard"),
    path('renter/gigrequest/<str:id>', views.gigrequest,name="gigrequest"),
    path('renter/gigoffer/', views.gigoffer,name="gigoffer"),
    path('renter/savepersonalinfo/', views.savepersonalinfo,name="savepersonalinfo"),
    path('renter/savedriverinfo/', views.savedriverinfo,name="savedriverinfo"),
    path('renter/generalinterest/<str:carid>', views.generalinterest,name="generalinterest"),
    path('renter/carreserve/<str:carid>', views.carreserve,name="carreserve"),
    path('renter/counteroffers/<str:id>', views.counteroffers,name="counteroffers"),
    path('renter/rejectgigride/', views.rejectgigride,name="rejectgigride"),
    path('renter/acceptcounteroffer/', views.acceptcounteroffer,name="acceptcounteroffer"),
    path('renter/runninggig/', views.runninggig,name="runninggig"),
    path('renter/invitedriver/', views.invitedriver,name="invitedriver"),
    path('renter/invitemember/', views.invitecustomer,name="invitecustomer"),
    path('renter/networkhome/', views.networkhome,name="networkhome"),
    path('renter/networkhome/renterlist', views.networkrenterlist,name="networkrenterlist"),
    path('renter/shareride/<str:rideid>', views.shareride,name="shareride"),
    path('renter/rideshared/', views.rideshared,name="rideshared"),
    path('renter/acceptsharedride/<str:shareid>', views.acceptsharedride,name="acceptsharedride"),
    path('renter/addowncar/', views.addowncar,name="addowncar"),
    path('renter/cardetails/<str:carid>', views.rentercardetails,name="rentercardetails"),

]
